### PR TITLE
fix(desktopapplications): split XDG_CURRENT_DESKTOP by colon for Ubuntu support

### LINKED ISSUE #232: Missing system desktop apps on Ubuntu 24.04
I noticed that on Ubuntu (24.04), when I launch walker for apps (so I guess elephants with desktopapplications), the system apps (like Settings, Tweaks, and so on) don't appear. No issue with other apps.

### PR DESCRIPTION
**Pull request by Kasui92**
On Ubuntu, XDG_CURRENT_DESKTOP is set to "ubuntu:GNOME" (colon-separated list). The current code compares the entire string against OnlyShowIn / NotShowIn values, so "GNOME" never matches "ubuntu:GNOME" and system apps like Settings are filtered out.

The XDG Desktop Entry spec mandates that XDG_CURRENT_DESKTOP is a colon-separated list of desktop identifiers. This patch splits it accordingly and checks if *any* component matches.

Closes #232

### CODE REVIEW

File: internal/providers/desktopapplications/query.go [hunk 1]
```diff
@@ -13,7 +13,23 @@ import (
 	"github.com/abenz1267/elephant/v2/pkg/pb/pb"
 )
 
-var desktop = os.Getenv("XDG_CURRENT_DESKTOP")
+var desktops = splitDesktops(os.Getenv("XDG_CURRENT_DESKTOP"))
+
+func splitDesktops(val string) []string {
```
Comment (abenz1267) [inline internal/providers/desktopapplications/query.go]: this isnt required at all. just strings.Split the env.

Comment (Kasui92) [reply internal/providers/desktopapplications/query.go]: Done!
